repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.0
  hooks:
    - id: gitleaks

- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint
      name: Lint Dockerfiles
      description: Runs hadolint to lint Dockerfiles
      language: system
      types: ["dockerfile"]
      entry: hadolint
      files: \.\/docker\/.*$
      exclude: \.terraform\/.*$

# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: "v1.76.0"
#   hooks:
#     - id: terraform_checkov
#       name: Checkov
#       description: Runs checkov on Terraform templates.
#       entry: hooks/terraform_checkov.sh
#       language: script
#       always_run: false
#       files: \.*$
#       exclude: \.terraform\/.*$
#       require_serial: true
