---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >-
  Provision SageMaker Notebook Classic and related IAM configuration. Clone the workshop codebase into the notebook to get started.
Parameters:
  NotebookName:
    Type: String
    Default: SM101NotebookClassic
    Description: Enter the name of the SageMaker notebook instance. Default is SM101NotebookClassic.

  DefaultCodeRepo:
    Type: String
    Default: https://github.com/aacecandev/mlops-desarrollo-y-operaciones-de-inteligencia-artificial
    Description: URL of the git code repository to clone in to the SageMaker notebook.

  VpcId:
    Type: String
    Description: VPC ID to use (e.g. vpc-xxxxxx), or blank to use default.
    Default: ''

  SubnetIds:
    Type: String
    Description: >-
      Comma-separated list of subnet IDs to use (e.g. subnet-xxxxxx), or blank to use all default subnets.
    Default: ''

Mappings:
  RegionMap:
    us-east-1:
      datascience: 'arn:aws:sagemaker:us-east-1:081325390199:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:us-east-1:081325390199:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:us-east-1:081325390199:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:us-east-1:081325390199:image/jupyter-server-3'
    us-east-2:
      datascience: 'arn:aws:sagemaker:us-east-2:429704687514:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:us-east-2:429704687514:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:us-east-2:429704687514:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:us-east-2:429704687514:image/jupyter-server-3'
    us-west-1:
      datascience: 'arn:aws:sagemaker:us-west-1:742091327244:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:us-west-1:742091327244:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:us-west-1:742091327244:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:us-west-1:742091327244:image/jupyter-server-3'
    us-west-2:
      datascience: 'arn:aws:sagemaker:us-west-2:236514542706:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:us-west-2:236514542706:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:us-west-2:236514542706:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:us-west-2:236514542706:image/jupyter-server-3'
    af-south-1:
      datascience: 'arn:aws:sagemaker:af-south-1:559312083959:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:af-south-1:559312083959:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:af-south-1:559312083959:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:af-south-1:559312083959:image/jupyter-server-3'
    ap-east-1:
      datascience: 'arn:aws:sagemaker:ap-east-1:493642496378:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-east-1:493642496378:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-east-1:493642496378:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-east-1:493642496378:image/jupyter-server-3'
    ap-south-1:
      datascience: 'arn:aws:sagemaker:ap-south-1:394103062818:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-south-1:394103062818:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-south-1:394103062818:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-south-1:394103062818:image/jupyter-server-3'
    ap-northeast-2:
      datascience: 'arn:aws:sagemaker:ap-northeast-2:806072073708:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-northeast-2:806072073708:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-northeast-2:806072073708:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-northeast-2:806072073708:image/jupyter-server-3'
    ap-southeast-1:
      datascience: 'arn:aws:sagemaker:ap-southeast-1:492261229750:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-southeast-1:492261229750:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-southeast-1:492261229750:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-southeast-1:492261229750:image/jupyter-server-3'
    ap-southeast-2:
      datascience: 'arn:aws:sagemaker:ap-southeast-2:452832661640:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-southeast-2:452832661640:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-southeast-2:452832661640:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-southeast-2:452832661640:image/jupyter-server-3'
    ap-southeast-3:
      datascience: 'arn:aws:sagemaker:ap-southeast-3:276181064229:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-southeast-3:276181064229:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-southeast-3:276181064229:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-southeast-3:276181064229:image/jupyter-server-3'
    ap-northeast-1:
      datascience: 'arn:aws:sagemaker:ap-northeast-1:102112518831:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ap-northeast-1:102112518831:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ap-northeast-1:102112518831:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ap-northeast-1:102112518831:image/jupyter-server-3'
    # TODO: ap-northeast-2 and ap-northeast-3 if available?
    ca-central-1:
      datascience: 'arn:aws:sagemaker:ca-central-1:310906938811:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:ca-central-1:310906938811:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:ca-central-1:310906938811:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:ca-central-1:310906938811:image/jupyter-server-3'
    eu-central-1:
      datascience: 'arn:aws:sagemaker:eu-central-1:936697816551:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-central-1:936697816551:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-central-1:936697816551:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-central-1:936697816551:image/jupyter-server-3'
    # TODO: eu-central-2 if available?
    eu-west-1:
      datascience: 'arn:aws:sagemaker:eu-west-1:470317259841:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-west-1:470317259841:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-west-1:470317259841:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-west-1:470317259841:image/jupyter-server-3'
    eu-west-2:
      datascience: 'arn:aws:sagemaker:eu-west-2:712779665605:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-west-2:712779665605:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-west-2:712779665605:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-west-2:712779665605:image/jupyter-server-3'
    eu-west-3:
      datascience: 'arn:aws:sagemaker:eu-west-3:615547856133:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-west-3:615547856133:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-west-3:615547856133:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-west-3:615547856133:image/jupyter-server-3'
    eu-north-1:
      datascience: 'arn:aws:sagemaker:eu-north-1:243637512696:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-north-1:243637512696:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-north-1:243637512696:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-north-1:243637512696:image/jupyter-server-3'
    eu-south-1:
      datascience: 'arn:aws:sagemaker:eu-south-1:592751261982:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:eu-south-1:592751261982:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:eu-south-1:592751261982:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:eu-south-1:592751261982:image/jupyter-server-3'
    # TODO: me-central-1 and me-south-1 if available?
    sa-east-1:
      datascience: 'arn:aws:sagemaker:sa-east-1:782484402741:image/datascience-1.0'
      datascience2: 'arn:aws:sagemaker:sa-east-1:782484402741:image/sagemaker-data-science-38'
      datascience3: 'arn:aws:sagemaker:sa-east-1:782484402741:image/sagemaker-data-science-310-v1'
      jlabv3: 'arn:aws:sagemaker:sa-east-1:782484402741:image/jupyter-server-3'

Resources:
  # Permissions for the SageMaker notebook environment:
  SageMakerExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'

  # If running on classic notebook instances, make sure widgets library is installed:
  NotebookConfig:
    Type: 'AWS::SageMaker::NotebookInstanceLifecycleConfig'
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub '${AWS::StackName}-LifecycleConfig'
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -e

              # Install extension for ipywidgets interactivity:
              sudo -u ec2-user -i <<'EOF'
              source /home/ec2-user/anaconda3/bin/activate JupyterSystemEnv
              jupyter labextension install @jupyter-widgets/jupyterlab-manager ipycanvas
              source /home/ec2-user/anaconda3/bin/deactivate
              EOF

  NotebookInstance:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      InstanceType: ml.t3.medium
      LifecycleConfigName: !GetAtt NotebookConfig.NotebookInstanceLifecycleConfigName
      NotebookInstanceName: !Ref NotebookName
      PlatformIdentifier: notebook-al2-v2
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      VolumeSizeInGB: 20
      DefaultCodeRepository: !Ref DefaultCodeRepo
