#!/bin/bash

DOCKERFILE_PATH="docker/Dockerfile.awscli"
DOCKER_CONTEXT_PATH="./docker"

docker build \
-t "${DOCKER_REGISTRY_USER_NAME}/${DOCKER_REGISTRY_IMAGE_NAME}:${DOCKER_REGISTRY_IMAGE_TAG}" \
-f "${DOCKERFILE_PATH}" \
"${DOCKER_CONTEXT_PATH}"

docker push "${DOCKER_REGISTRY_USER_NAME}/${DOCKER_REGISTRY_IMAGE_NAME}:${DOCKER_REGISTRY_IMAGE_TAG}"
